version: '2.3'

services:
    db:
        image: postgres:10-alpine
        restart: always
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
          - ./data/postgres:/var/lib/postgresql/data
    php:
        build:
            context: docker/php
            args:
                TIMEZONE: ${TIMEZONE}
        restart: always
        ports:
            - 9001:9000
        links:
            - db
        volumes:
            - ${SYMFONY_APP_PATH}/symfony:/var/www/symfony
            - ./symfony/var/logs:/var/www/symfony/var/logs
            - ./symfony/var/cache:/var/www/symfony/var/cache
    nginx:
        build: docker/nginx
        restart: always
        ports:
            - ${SYMFONY_APP_PORT}:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./symfony/var/serverlogs:/var/log/nginx
    elk:
        image: willdurand/elk
        restart: always
        ports:
            - ${KIBANA_PORT}:80
        volumes:
            - ./docker/elk/logstash:/etc/logstash
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
